import os

#Class with the Neccesary Constants for the System
class constantes:
  #Paths for read Files
  RUTA_BASE= os.getcwd()+ os.sep
  FOLDER_RESPALDOS=RUTA_BASE+"respaldos"+os.sep
  FOLDER_DOCUMENTS=RUTA_BASE+"documents"+os.sep
  FOLDER_ZIP=RUTA_BASE+"temp_zips"+os.sep
  
  #Required for Panels data
  WIDTH_PORCENT=0.8
  HEIGTH_PORCENT=0.8
  MIN_SIZE_EMPTY_ROW=20
  MIN_SIZE_EMPTY_COLUMN=20
  FG_DEFAULT_BACKGROUND=("#70A2D1","#323757")
  
  #User Types
  ACCESO_ADMIN=0
  ACCESO_COORDINADOR=1
  ACCESO_DIRECTOR=2
  ACCESO_SECRETARIA=3
  ACCESO_SUBDIRECTOR=4
  
  #UI Component Types
  UI_BUTTON=0
  UI_RADIOBUTTON=1
  UI_LABEL=2
  UI_LABEL_IMAGE=3
  UI_CHECKBUTTON=4
  UI_TABLE=5
  UI_COMBOBOX=6
  UI_TEXTFIELD=7
  
  
  #UI Panels Ids
  PANTALLA_INICIO="inicio"
  PANTALLA_WELCOME="welcome"
  PANTALLA_REGISTRO_USUARIO="registroUsuario"
  PANTALLA_REGISTRO_PERSONAL="registroPersonal"
  PANTALLA_REGISTRO_FORMATO="registroForm"
  PANTALLA_REGISTRO_CALIFICACION="registroCalif"
  PANTALLA_REGISTRO_DISP_HORARIO="registroDisp"
  PANTALLA_REGISTRO_AREA_FORMACION="registroAreas"
  PANTALLA_REGISTRO_HORARIO="registro_horario"
  PANTALLA_PROCESO_INSCRIPCION="inscripcion"
  PANTALLA_PROCESO_PLANIFICACION="planificacion"
  PANTALLA_PROCESO_RENDIMIENTO="rendimiento"
  PANTALLA_CONSULTA_PERSONAL="consultaPersonal"
  PANTALLA_CONSULTA_ESTUDIANTES="consultaEstudiantes"
  PANTALLA_CONSULTA_PROFESORES="consultaProf"
  PANTALLA_CONSULTA_SECCIONES="consultaSecciones"
  PANTALLA_CONSULTA_MOMENTOS="consulta_momentos"
  PANTALLA_CONSULTA_DISP_HORARIO="consultaDisp"
  PANTALLA_CONSULTA_AREAS_FORMACION="consultaAreas"
  PANTALLA_CONSULTA_AREAS_DOCENTE="consultaAreasDocente"
  PANTALLA_CONSULTA_MAT_PEND="consultaMatPend"
  PANTALLA_CONSULTA_DESCARGAS="consultar_descargas"
  
  PANTALLA_SERVICIO_ESTADISTICA="estadistica"
  PANTALLA_SERVICIO_AUDITORIA="auditoria"
  PANTALLA_SERVICIO_GESTION_USUARIO="gestionUsuario"
  PANTALLA_SERVICIO_RESPALDO_BD="respaldoBD"
  PANTALLA_SERVICIO_REACTIVAR_MOMENTO="reactivarMom"
  PANTALLA_AYUDA_INFORMACION="info_institucion"
  PANTALLA_UPDATE_ESTUDIANTE="update_estudiante"
  PANTALLA_SERVICIO_REORGANIZAR_SECCIONES="organizar_secciones"
  PANTALLA_RECUPERAR_PASSWORD="recuperar_pass"
  PANTALLA_DESCARGAR_FORMATOS="download_forms"
  PANTALLA_DESCARGAR_CONSTANCIAS="download_constancias"
  PANTALLA_UPDATE_USER="update_user"
  PANTALLA_DESCARGAR_CARNETS="download_carnets"
 
  #Panels Ids for The Process
  PANTALLA_PROCESO_INSCRIPCION_2="inscripcion_nuevo"
  PANTALLA_PROCESO_INSCRIPCION_3="inscripcion_regular"
  PANTALLA_PROCESO_INSCRIPCION_4="inscripcion_final"
  PANTALLA_PLANIF_FORMATO1="formatos1"
  PANTALLA_PLANIF_FORMATO2="formatos2"
  PANTALLA_RENDIMIENTO_GESTION_CALIF="rendimiento_calif"
  PANTALLA_RENDIMIENTO_MAT_PEND="rendimiento_mat_pend"
  PANTALLA_RENDIMIENTO_SABANA_NOTAS="rendimiento_sabana"
  PANTALLA_RENDIMIENTO_GESTION_CALIF_FINALES="rendimiento_calif_finales"
  PANTALLA_RENDIMIENTO_IDENTIFIC_MATERIA="rendimiento_GestionCalifiaciones_Identific"
  PANTALLA_RENDIMIENTO_IDENTIFIC_MATERIA_PEND="rendimiento_MateriaPendiente_Identific"
  PANTALLA_PLANIFIC_CRONOG1="cronog1"
  PANTALLA_PLANIFIC_CRONOG2="cronog_inscripciones"
  PANTALLA_PLANIFIC_CRONOG3="cronog_mat_pendiente"
  PANTALLA_PLANIFIC_CRONOG4="cronog_mom1"
  PANTALLA_PLANIFIC_CRONOG5="cronog_mom2"
  PANTALLA_PLANIFIC_CRONOG6="cronog_mom3"
  
  TRANSPARENT_COLOR='magenta'
  
  #Input Text Types
  CADENA_SOLOTEXTO=0
  CADENA_SOLONUMERO=1
  CADENA_PASSWORD=2
  CADENA_DIRECCION=3
  CADENA_TELEFONO=4
  CADENA_CORREO=5
  CADENA_ALFANUMERICA=6
  CADENA_USER=7
  CADENA_FECHA=8
  CADENA_YEAR=9
  CADENA_AÑO_ESCOLAR=10
  CADENA_CALIFICACION=11
  
  #Request Types for Documents
  REQUEST_READ_EXCEL=0
  REQUEST_WRITE_CSV=1
  REQUEST_READ_CSV=2
  REQUEST_MODIFIC_EXCEL=3
  REQUEST_WRITE_EXCEL_FROM_EXISTENT_FORMAT=4
  REQUEST_DOWNLOAD=5
  REQUEST_WRITE_NOTAS_CERTIFICADAS=6
  REQUEST_WRITE_CRONOGRAM=7
  
  #Request Response for Documents
  REQUEST_RESULT_WRITE_CSV_SUCCESS=2
  REQUEST_RESULT_READ_CSV_SUCCESS=3
  REQUEST_RESULT_OPERATION_SUCCEESS_NO_MESSAGE=7
  REQUEST_RESULT_GENERATE_DOCUMENT_WITH_MESSAGE=8
  REQUEST_RESULT_DOWNLOAD_SUCCESS=9
  REQUEST_RESULT_ERROR_WRITE_CSV=-6
  REQUEST_RESULT_ERROR_READ_CSV=-7
  REQUEST_RESULT_ERROR_NO_REFERENCE_EXCEL=-8
  REQUEST_RESULT_ERROR_REFERENCE_EXCEL=-9
  REQUEST_RESULT_ERROR_ACCESS=-10
  REQUEST_RESULT_ERROR_GET_DATA=-11
  REQUEST_RESULT_ERROR_FOUND_END_ROW=-12
  REQUEST_RESULT_ERROR_INVALID_CONTENT=-13
  
  #Combo Box Events
  COMBOBOX_SHOW_AREAS_FORMACION_DOCENTES=0
  COMBOBOX_LOAD_AREA_FORMACION=1
  COMBOBOX_LOAD_DATA_AUDITORIA_STADITICAS=2
  COMBOBOX_LOAD_MOMENTOS_ACADEMICOS=3
  COMBOBOX_SHOW_INFO_MATERIA_PENDIENTE=4
  COMBOBOX_CHANGE_TIMES_DISP_HORARIOS=5
  COMBOBOX_LOAD_WORKERS_USERS=6
  COMBOBOX_LOAD_WORKERS_DISP_HORARIOS=7
  COMBOBOX_GET_FULL_DATA_WORKER_REGISTRO_HORARIOS=8
  COMBOBOX_SHOW_MODIFICAR_FORMATO_REFERENCE_DATA=9
  COMBOBOX_REMOVE_ALL_ITEMS_ON_LOAD=10
  COMBOBOX_LOAD_DATA_AREA_FORMACION=11
  COMBOBOX_GET_DATA_SECCION_REGISTRO_HORARIO=12
  COMBOBOX_LOAD_WORKERS_HORARIOS=13
  COMBOBOX_LOAD_WORKERS_FOR_REGISTER=14
  COMBOBOX_LOAD_STUDENTS=15
  COMBOBOX_LOAD_SECCION=16
  COMBOBOX_SET_DATA_STUDENTES_SECCION=17
  COMBOBOX_LOAD_PROFESORES=18
  COMBOBOX_LOAD_PREGUNTAS_SECRETAS=19
  COMBOBOX_CHANGE_RESPUESTA_SECRETAS=20
  COMBOBOX_SHOW_FORMATOS_DESCARGABLE_SECCION=21
  COMBOBOX_LOAD_WORKERS_CARNETS_AND_CONSTANCIAS=22
  COMBOBOX_LOAD_LIST_FORMATOS=23
  COMBOBOX_SET_DATA_HORARIO=24
  COMBOBOX_LOAD_SECCION_RENDIMIENTO=25
  COMBOBOX_SET_STUDENT_DATA_RENDIMIENTO=26
  COMBOBOX_LOAD_SECCION_RENIDMIENTO_FILTER_MATERIA_PENDIENTE=27
  COMBOBOX_SET_DATA_CRONOGRAMA=29
  COMBOBOX_SET_DATA_AUDITORIA=30
  COMBOBOX_LOAD_WORKER_POSIBLE_DIRECTOR=31
  COMBOBOX_REACTIVATE_MOMENTS_SHOW_OPTION=32
  COMBOBOX_UPDATE_USER=33
 
  #Label Events
  LABEL_LOAD_WORKER_SELECTED_INFO=0
  LABEL_LOAD_HISTORIAL_INFO=1
  LABEL_LOAD_CRONOGRAM_INFO=2
  LABEL_RECUPERAR_PASS=5
  
  #TextField Events
  TEXFIELD_SET_FOLDER_RESPALDO_BD_TEXT=0
  TEXTFIELD_DISABLED=1
  TEXTFIELD_DISABLED_AND_SET_TEXT_ZERO=2
  TEXTFIELD_READONLY=3
  TEXTFIELD_ACTIVATE_ON_LOAD=4
   
  #List Box Events
  LISTBOX_SET_WORKERS_USERS_CANDIDATOS_DATA=0
  LISTBOX_SET_WORKERS_DATA=1
  LISTBOX_SET_LIST_USERS_DATA=2
  LISTBOX_SET_AREAS_FORMACION_DISPONIBLES_DOCENTES=3
  LISTBOX_SET_DATA_FORMATO=4
  LISTBOX_SET_VALUE_TO_REMOVE_COLUMN_FORMATO=5
  LISTBOX_SET_STUDENT_DATA_SELECTED=6
  LISTBOX_SET_STUDENT_INTERCAMBIO_DATA_SELECTED=7
  LISTBOX_SET_FIELD_TO_REMOVE_FORMATO=8
  
  #Table Events
  TABLE_LOAD_DATA_GESTION_USUARIOS=0
  TABLE_LOAD_DATA_CALIFICATIONS_STUDENTS=1
  TABLE_SET_DATA_DEFINITIVE_CALIFICATION_STUDENT=2
  
  #Nuevo Ingreso Constants
  NUEVO_INGRESO_FIRST_YEAR=0
  NUEVO_INGRESO_NO_FIRST_YEAR=1
  NUEVO_INGRESO_UPDATE=2
  
  #System Events
  EV_LOGIN=0
  EV_LOGOUT=1
  EV_EXIT=2
 
  #Register Events
  EV_REGISTRAR_PERSONAL=3
  EV_REGISTRAR_FORMATO=4
  EV_REGISTRAR_DISP_HORARIO=5
  EV_REGISTRAR_AREA_FORMACION=6
  EV_REGISTRAR_HORARIO=7
  EV_UPDATE_HORARIO=8
  EV_UPDATE_TRABAJADOR=9
  EV_UPDATE_DISP=10
  EV_UPDATE_FORMATO=11
  EV_UPDATE_AREA=12
  
  #Service Events
  EV_AUDITORIA=13
  EV_VER_ESTADITICA=14
  EV_ACTIVAR_MOM=15
  EV_ACTUALIZAR_USUARIO=16
  EV_REGISTRAR_USUARIO=17
  EV_SERVICIO_RESPALDO_BD=18
  EV_GESTION_USER_DESBLOQUEAR=19
  EV_GESTION_USER_RESTORE_PASS=20
  EV_GESTION_USER_DELETE_USER=21
  EV_GESTION_USER_CHANGE_PASS=22
  EV_GESTION_USER_CHANGE_PERMISOS=23
  EV_UPDATE_PASS=24
  EV_UPDATE_USER=25
  EV_NUEVO_USUARIO=26
  EV_UPDATE_SECCION=27
  EV_UPDATE_ESTUDIANTE=28
  EV_REESTABLECER_MOMENTO=29

  #UI Events
  EV_ACTIVAR_ACTUALIZAR_PERSONAL=30
  EV_ACTIVAR_ACTUALIZAR_ESTUDIANTE=31
  EV_ACTIVAR_ACTUALIZAR_HORARIO=32
  EV_ACTIVAR_ACTUALIZAR_DISP=33
  EV_ACTIVAR_ACTUALIZAR_AREA=34
  EV_ACTIVAR_COMPS_UPDATE=35
  EV_ACTIVAR_DOWNLOAD_CARNETS=36
  EV_ACTIVAR_DOWNLOAD_FORMATOS=37
  EV_ACTIVAR_DOWNLOAD_CONSTANCIAS=38
  EV_ACTIVAR_RECUPERAR_PASS1=39
  EV_ACTIVAR_RECUPERAR_PASS2=40
  EV_RESET=41
  EV_ABRIR_FOTO=42
  EV_ABRIR_FILE_SINGLE=43
  EV_AGREGAR_AREA_DOCENTE=45
  EV_BORRAR_AREA_DOCENTE=46
  EV_MOVER_ESTUD=47
  EV_INTERCAMBIAR_ESTUDS=48
  EV_INCORPORAR_ESTUD=49
  EV_LOAD_LOGIN=50
  EV_LOAD_INICIO=51
  EV_VOLVER=52
 
  #Consult Events
  EV_CONSULTAR_PERSONAL=53
  EV_CONSULTAR_ESTUDIANTE=54
  EV_CONSULTAR_REPORTES=55
  EV_CONSULTAR_PROFESORES=56
  EV_CONSULTAR_SECCIONES=57
  EV_CONSULTAR_HORARIOS=58
  EV_CONSULTAR_MOMENTOS=59
  EV_CONSULTAR_DISP_HORARIO=60
  EV_CONSULTAR_AREA_FORMACION=61
  EV_CONSULTAR_AREAS_DOCENTES=62
  EV_CONSULTAR_DESCARGAS=63
  EV_CONSULTAR_MAT_PEND=64 
 
  # Events Required for Process
  EV_FINALIZAR_PROCESO=65
  EV_PROCESO_NEXT=66
  EV_SEARCH_ESTUD=67
  
  #Inscriptions Events
  EV_INSCRIPCION_NUEVO_INGRESO=68
  EV_INSCRIPCION_REGULAR=69
  EV_NEXT_INSCRIP=70
  EV_FINISH_INSCRIP=71
  EV_INIT_EXPEDIENTE=72
  
  #Planifications Events
  EV_PLANIFIC_CRONOGRAMA=73
  EV_PLANIFIC_FORMATOS=74
  EV_REPORTE_CRONOG=75
  EV_ADD_COL_FORMAT=76
  EV_DELETE_COL_FORMAT=77
  EV_MODIF_COL_FORMAT=78
  EV_GESTION_CRONOG1=79
  EV_GESTION_CRONOG2=80
  EV_GESTION_CRONOG3=81
  EV_GESTION_CRONOG4=82
  EV_GESTION_CRONOG5=83
  EV_INIT_GESTION_CRONOG=84
  EV_GESTION_FORMATOS=85 
  EV_MODIFIC_SOURCE_FORMATO=86
  EV_MODIFIC_CONTENT_FORMATO=87
  
  #Rendimientos Events
  EV_RENDIMIENTO_GESTION_CALIFIC=88
  EV_RENDIMIENTO_SABANA=89
  EV_RENDIMIENTO_REVISION=90
  EV_RENDIMIENTO_MATERIA_PEND=91
  EV_RENDIMIENTO_NOTAS_CERTIFIC=92
  EV_MODIFIC_CALIFIC=93
  EV_ESTIMULAR_AREA=94
  EV_DELETE_CALIFIC=95
  EV_REMOVE_ESTIMULACION=96
  EV_GENERAR_SABANA=97
  EV_GESTIONAR_CALIF=98
  EV_GESTIONAR_MAT_PEND=99
  EV_REGISTRAR_INTENTO_MAT_PEND=100
  EV_MODIFIC_CALIF_FINAL=101
  EV_REPORTE_NOTAS=102
  EV_REPORTE_NOTAS_AÑO=103
  EV_REPORTE_NOTAS_MOMENTO=104
  EV_REPORTE_EVALUACION_SECCION=105
  EV_MODIFIC_EVALUACION=106
  EV_REGISTRAR_CALIFICACION=107
  
  #Reports and Downloads Events
  EV_REPORTE_NOMINA_SECCION=108
  EV_REPORTE_ASISTENCIA_SECCION=109
  EV_REPORTE_INFO_ESTUDIANTE=110
  EV_REPORTE_INFO_TRABAJADOR=111
  EV_REPORTE_DISPONIBILIDAD_HORARIO=112
  EV_REPORTE_ESTUDIANTE_MAT_PENDIENTE=113
  EV_DESCARGAR_FORMATO_ANONIMO=114
  EV_DESCARGAR_CONSTANCIA=115
  EV_DESCARGAR_HORARIO=116
  EV_DESCARGAR_FORMATO=117
  EV_DESCARGA_CARNET=118
  EV_REPORTE_ACCIONES_USUARIOS=119
  EV_REPORTE_DESCARGAS=120
  EV_GENERAR_NOMINA_TRABAJ=121
  EV_DOWNLOAD_EXPEDIENTE_ESTUD=122
  EV_DOWNLOAD_EXPEDIENTE_PERSONAL=123
  EV_DESCARGAR_HORARIO_SECCION=124
  EV_LIMPIAR_REPORTES=125

  #data Base Tables Names
  NUM_TABLAS=30 
  TABLA_EXPEDIENTE="expediente"
  TABLA_HORARIO="horario"
  TABLA_TRABAJADOR="trabajador"
  TABLA_USUARIO="usuario"
  TABLA_PROFESOR="profesor"
  TABLA_ESTUDIANTE="estudiante"
  TABLA_CRONOGRAMA="cronograma"
  TABLA_AREA_FORMACION="area_formacion"
  TABLA_SECCION="seccion"
  TABLA_FORMATO="formato"
  TABLA_FECHA="fecha"
  TABLA_REPORTE="reporte"
  TABLA_PREGUNTA_SECRETA="pregunta_secreta"
  TABLA_MOMENTO="momento"
  TABLA_CALIFICACION="calificacion"
  TABLA_CALIF_MOM="calif_momento"
  TABLA_CALIFICACION_FINAL="calificacion_final"
  TABLA_REPRESENTANTE="representante"
  TABLA_AREA_DOCENTE="area_dictada_docentes"
  TABLA_DISP_HORARIO="disponibilidad_horario"
  TABLA_MATERIA_PENDIENTE="materia_pendiente"
  TABLA_CALIF_PENDIENTE="calific_pendiente"
  TABLA_DIRECCION="direccion";
  TABLA_DESCARGA_DOCUMENTO="descarga_documentos"
  TABLA_ESTATUS_TRABAJ="estatus_trabaj"
  TABLA_ESTATUS_ESTUD="estatus_estud"
  TABLA_INTENTOS_USUARIO="intentos_usuario"
  TABLA_AÑOS_INCORPORADOS="años_incorporados"
  TABLA_NOMBRE="nombre"
  TABLA_CARGO="cargo"
  
  #Data Base Key Fields Ids
  CLAVE_EXPEDIENTE="id_exp"
  CLAVE_HORARIO="id_hor"
  CLAVE_TRABAJADOR="CI_trabaj"
  CLAVE_USUARIO="usuario"
  CLAVE_PROFESOR="id_prof"
  CLAVE_ESTUDIANTE="CI_estud"
  CLAVE_AREA_FORMACION="nomb_area"
  CLAVE_SECCION="id_secc"
  CLAVE_FORMATO="tipo"
  CLAVE_CRONOGRAMA="año_escolar"
  CLAVE_REPORTE="id_reporte"
  CLAVE_MOMENTO="id_mom"
  CLAVE_FECHA="id_fecha"
  CLAVE_CALIFICACION="id_calif"
  CLAVE_CALIF_MOM="id_mom_c"
  CLAVE_CALIFICACION_FINAL="id_final_c"
  CLAVE_REPRESENTANTE="CI_repres"
  CLAVE_AREA_DOCENTE="id_docente_Area"
  CLAVE_DISP_HORARIO="id_disp"
  CLAVE_MATERIA_PENDIENTE="id_pend"
  CLAVE_CALIF_PENDIENTE="id_calif_pen"
  CLAVE_DIRECCION="id_dir";
  CLAVE_NOMBRE="id_nombre"
  CLAVE_ESTATUS_ESTUD="id_est"
  CLAVE_ESTATUS_TRABAJ="id_est_trabaj"
  CLAVE_INTENTOS_USUARIO="id_intentos"
  CLAVE_AÑOS_INCORPORADOS="id_years_in"
  CLAVE_DESCARGA_DOCUMENTO="id_descarg"
  CLAVE_PREGUNTA_SECRETA="id_pregunta"
  CLAVE_CARGO="id_cargo"
  
  #foregein Keys Ids
  FORANEOS_EXPEDIENTE=[False,False,False,False,False]
  CAMPOS_EXPEDIENTE=[CLAVE_EXPEDIENTE,"src_exp","src_foto","fecha_registro","modificado"] 
  FORANEOS_HORARIO=[False,False,False,False]
  CAMPOS_HORARIO=[CLAVE_HORARIO,"src_hor","turno","modificado"]
  FORANEOS_TRABAJADOR=[False,TABLA_NOMBRE,False,False,TABLA_EXPEDIENTE,TABLA_HORARIO,TABLA_CARGO,TABLA_ESTATUS_TRABAJ,False]
  CAMPOS_TRABAJADOR=[CLAVE_TRABAJADOR,CLAVE_NOMBRE,"correo","telefono",CLAVE_EXPEDIENTE,CLAVE_HORARIO,CLAVE_CARGO,CLAVE_ESTATUS_TRABAJ,"modificado"] 
  FORANEOS_CARGO=[False,False,False,False,False]
  CAMPOS_CARGO=[CLAVE_CARGO,"cargo","cargo_ministerio","modificado","codigo_cargo"]
  FORANEOS_USUARIO=[False,False,TABLA_TRABAJADOR,False,False,TABLA_INTENTOS_USUARIO,False,False]
  CAMPOS_USUARIO=[CLAVE_USUARIO,"password",CLAVE_TRABAJADOR,"nivel_acceso","foto",CLAVE_INTENTOS_USUARIO,"bloqueado","modificado"]
  FORANEOS_PROFESOR=[False,TABLA_TRABAJADOR,TABLA_SECCION,False]
  CAMPOS_PROFESOR=[CLAVE_PROFESOR,CLAVE_TRABAJADOR,"seccion_guia","modificado"]
  FORANEOS_AREA_FORMACION=[False,False,TABLA_AÑOS_INCORPORADOS,False]
  CAMPOS_AREA_FORMACION=[CLAVE_AREA_FORMACION,"incorporada",CLAVE_AÑOS_INCORPORADOS,"modificado"]
  FORANEOS_SECCION=[False,False,False,TABLA_HORARIO,False,False,False,False]
  CAMPOS_SECCION=[CLAVE_SECCION,"año","letra",CLAVE_HORARIO,"total_estud","maximo_estud","minimo_estud","modificado"]
  FORANEOS_ESTUDIANTE=[False,TABLA_NOMBRE,TABLA_ESTATUS_ESTUD,TABLA_SECCION,TABLA_EXPEDIENTE,TABLA_REPRESENTANTE,False,False,TABLA_DIRECCION,False,False]
  CAMPOS_ESTUDIANTE=[CLAVE_ESTUDIANTE,CLAVE_NOMBRE,CLAVE_ESTATUS_ESTUD,CLAVE_SECCION,CLAVE_EXPEDIENTE,CLAVE_REPRESENTANTE,"genero","nacimiento",CLAVE_DIRECCION,"parentesco","modificado"]
  FORANEOS_FORMATO=[False,False,False]
  CAMPOS_FORMATO=[CLAVE_FORMATO,"src_form","modificado"]
  FORANEOS_CRONOGRAMA=[False,False,False,False]
  CAMPOS_CRONOGRAMA=[CLAVE_CRONOGRAMA,"inicio","cierre","modificado"]
  FORANEOS_REPORTE=[False,TABLA_USUARIO,False,False,False,False,False,False]
  CAMPOS_REPORTE=[CLAVE_REPORTE,CLAVE_USUARIO,"fecha","hora","tipo","razon","motivo","modificado"]
  FORANEOS_PREGUNTA_SECRETA=[False,TABLA_USUARIO,False,False,False,False]
  CAMPOS_PREGUNTA_SECRETA=[CLAVE_PREGUNTA_SECRETA,CLAVE_USUARIO,"respuesta","pregunta","numero","modificado"]
  FORANEOS_MOMENTO=[False,False,False,False,False,False,False]
  CAMPOS_MOMENTO=[CLAVE_MOMENTO,"abierto","culminado","modificado","fecha_limite","hora_limite","fecha_inicio"]
  FORANEOS_FECHA=[False,TABLA_MOMENTO,TABLA_CRONOGRAMA,False,False,False,False]
  CAMPOS_FECHA=[CLAVE_FECHA,CLAVE_MOMENTO,CLAVE_CRONOGRAMA,"razon","fecha","fecha_cierre","modificado"]
  FORANEOS_CALIFICACION=[False,TABLA_CALIF_MOM,False,False,False]
  CAMPOS_CALIFICACION=[CLAVE_CALIFICACION,CLAVE_CALIF_MOM,"valor","numero","modificado"]
  FORANEOS_CALIF_MOM=[False,TABLA_MOMENTO,TABLA_CALIFICACION_FINAL,False,False,False,False,False]
  CAMPOS_CALIF_MOM=[CLAVE_CALIF_MOM,CLAVE_MOMENTO,CLAVE_CALIFICACION_FINAL,"prom","definitiva","estimulacion","año","modificado"]
  FORANEOS_CALIFICACION_FINAL=[False,TABLA_ESTUDIANTE,False,TABLA_AREA_FORMACION,False,False]
  CAMPOS_CALIFICACION_FINAL=[CLAVE_CALIFICACION_FINAL,CLAVE_ESTUDIANTE,"año",CLAVE_AREA_FORMACION,"valor","modificado"] 
  FORANEOS_REPRESENTANTE=[False,TABLA_NOMBRE,False,False,False,TABLA_DIRECCION,False,]
  CAMPOS_REPRESENTANTE=[CLAVE_REPRESENTANTE,CLAVE_NOMBRE,"telef","correo","ocupacion",CLAVE_DIRECCION,"modificado"]
  FORANEOS_AREA_DOCENTE=[False,TABLA_PROFESOR,TABLA_AREA_FORMACION,False]
  CAMPOS_AREA_DOCENTE=[CLAVE_AREA_DOCENTE,CLAVE_PROFESOR,CLAVE_AREA_FORMACION,"modificado"] 
  FORANEOS_DISP_HORARIO=[False,TABLA_TRABAJADOR,False,False,False,False,False,False,False]
  CAMPOS_DISP_HORARIO=[CLAVE_DISP_HORARIO,CLAVE_TRABAJADOR,"turno","disp_lunes","disp_martes","disp_miercoles","disp_jueves","disp_viernes","modificado"]
  FORANEOS_MATERIA_PENDIENTE=[False,TABLA_ESTUDIANTE,False,TABLA_AREA_FORMACION,False,False]
  CAMPOS_MATERIA_PENDIENTE=[CLAVE_MATERIA_PENDIENTE,CLAVE_ESTUDIANTE,"max_calif",CLAVE_AREA_FORMACION,"año","modificado"]
  FORANEOS_CALIF_PENDIENTE=[False,TABLA_MATERIA_PENDIENTE,False,False,False,False]
  CAMPOS_CALIF_PENDIENTE=[CLAVE_CALIF_PENDIENTE,CLAVE_MATERIA_PENDIENTE,"intento","valor","fecha","modificado"]
  FORANEOS_DIRECCION=[False,False,False,False,False]
  CAMPOS_DIRECCION=[CLAVE_DIRECCION,"sector","parroquia","casa","modificado"]
  FORANEOS_INTENTOS_USUARIO=[False,False,False,False,False]
  CAMPOS_INTENTOS_USUARIO=[CLAVE_INTENTOS_USUARIO,"num_intentos","last_fecha","last_hora","modificado"]
  FORANEOS_AÑOS_INCORPORADOS=[False,False,False,False,False,False,False]
  CAMPOS_AÑOS_INCORPORADOS=[CLAVE_AÑOS_INCORPORADOS,"1_año","2_año","3_año","4_año","5_año","modificado"]
  FORANEOS_ESTATUS_ESTUD=[False,False,False,False,False,False,False,False,False]
  CAMPOS_ESTATUS_ESTUD=[CLAVE_ESTATUS_ESTUD,"estatus","salud","cedulado","last_year","fecha_inscrip","fecha_ingreso","plantel_procedencia","modificado"]  
  FORANEOS_ESTATUS_TRABAJ=[False,False,False,False,False]
  CAMPOS_ESTATUS_TRABAJ=[CLAVE_ESTATUS_TRABAJ,"estatus","service_years","fecha_ingreso","modificado"]
  FORANEOS_DESCARGA_DOCUMENTO=[False,TABLA_TRABAJADOR,TABLA_FORMATO,False,False,False,False]
  CAMPOS_DESCARGA_DOCUMENTO=[CLAVE_DESCARGA_DOCUMENTO,CLAVE_TRABAJADOR,CLAVE_FORMATO,"fecha","hora","tipo_descarga","modificado"]
  FORANEOS_NOMBRE=[False,False,False,False,False,False]
  CAMPOS_NOMBRE=[CLAVE_NOMBRE,"nombre","s_nombre","apellido","s_apellido","modificado"]

  #default values Required 
  MAXIMO_EVALUACIONES=6
  PASS_USER_DEFAULT="Axah5512$"
  DEFAULT_USER_ICON="fotos/user_login.jpg"
  SERVER="http://localhost/Instituto/"
  SERVER_BD="Instituto"

